apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jenkins
            image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
