apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name }}
spec:
  type: {{ Values.service.type }}
  selector:
    app: jenkins-server
  ports:
    - port: {{ Values.containerports.port }}
      nodePort: {{ Values.service.nodePort }}
